### ISSUE TITLE
m list shows 4.4.0 but only rc10 is available

### ISSUE THREAD

**Issue by niccottrell** [aheckmann/m#63] opened 2020-06-24 11:09 UTC
`m list` returns a list including 4.4.0, but `m 4.4.0` fails with `tar: Error opening archive: Unrecognized archive format`.

http://dl.mongodb.org/dl/src/ only include 4.4.0-rc10 and `m 4.4.0-rc10` succeeds.

I guess the list should output 4.4.0-rc10 only at this point.

**Comment by stennie** [comment] 2020-12-07 10:00
Hi @niccottrell,

Looks like this was a transient problem before 4.4.0 was released. I'm not sure what happened with the downloads at the time, but closing since this can no longer be reproduced.

Regards,
Stennie

**Closed by stennie** 2020-12-07 10:00 UTC
